version: 0.2
env:
  secrets-manager:
    LOGIN: prod/sonar:sonartoken
    HOST: prod/sonar:HOST
    Organization: prod/sonar:Organization
    Project: prod/sonar:Project    
  pre_build:
    commands:
      - dotnet tool install --global dotnet-sonarscanner --version 4.7.1
  build:
    commands:
      - dotnet <path to SonarScanner.MSBuild.dll> begin /k:"project-key" 
      - dotnet build <path to solution.sln>
      - dotnet <path to SonarScanner.MSBuild.dll> end
      - dotnet publish -c release -o ./build_output SampleCore.csproj     
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
